name: Running the deploy.yml

on:
  push:
    branches:
      - main
      - master

jobs:
  build and push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # ./docker/user.Dockerfile ..
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/payments-app:latest

      - name: Verify Pushed Images
        run: docker pull aadeshak/payments-app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop payments-app || true
            docker rm payments-app || true
            docker rmi aadeshak/payments-app:latest || true
            docker pull aadeshak/payments-app:latest
            docker run -d -p 3005:3000 --name payments-app aadeshak/payments-app:latest
